Edited a couple of lines in the shell scripts
Hjdskes/hjdskes.github.io pull request #1
Opened 2017-03-17 09:31 UTC by xinye1

Hi Jente

Thank you very much for the tutorial for setting up Github to work with Hugo 👍 (very helpful and a big time saver for me!), which I followed to create [my own](https://xinye1.github.io), and of course your post on this will be clearly referenced in my post that documents it :)

Just wanted to point out that `setup.sh` and `deploy.sh` both seem to have a bit missed out (or am I missing something?), namely

1. `setup.sh` - in line 33 missing `add`
2. `deploy.sh` - in line 26 missing `public/`

Please let me know if this is the case, or that I'm completely wrong. I hope to hear from you before I publish my post on this :)

Thanks again!

Xinye

2017-03-17 17:01 UTC, Hjdskes requested changes
The fix to the `git worktree` command is indeed correct! If you can let me know whether you want to change `deploy.sh` or not, I will merge the PR.

Thanks!

2017-03-17 17:01 UTC, Hjdskes commented on deploy.sh
> +git rm -rf public/*
The line above this actually changes the directory to `public/`, see [how do I use `pushd` and `popd` commands](http://unix.stackexchange.com/questions/77077/how-do-i-use-pushd-and-popd-commands), so the change you made is not correct.

However, these three lines can probably be replaced with `rm -rf public/`; I don't recall if there was a reason to do it the way it is now. If you want to make that change, I'd happily merge it :)

2017-03-17 17:27 UTC, xinye1 commented on deploy.sh
> +git rm -rf public/*
Of course, I ignored `pushd` by mistake. And I agree that the single line `rm -rf public/` simplifies things which is good if you can't remember why not earlier, although keeping `git` in front saves another `git add` line, so `git rm -rf public/` in the end, correct?

2017-03-17 18:19 UTC, Hjdskes commented on deploy.sh
> +git rm -rf public/*
Wait, we don't want to delete the whole folder because we need to preserve the `.git/` directory inside it. We should leave this script as-is ;)

2017-03-17 23:04 UTC, xinye1 commented on deploy.sh
> +git rm -rf public/*
Sure, makes sense. Shall we just merge the `setup.sh` then? :)

2017-03-17 23:44 UTC, Hjdskes commented on deploy.sh
> +git rm -rf public/*
Yup! If you can fix your commit I'll merge it!

2017-03-18 00:36 UTC, xinye1 commented on deploy.sh
> +git rm -rf public/*
Sorry, just a final thought. In `deploy.sh` the 3 lines could be merged into `git rm -rf public/*` which only deletes everything inside `public/`, and the folder would be preserved. Would you agree to that?

2017-03-18 00:42 UTC, Hjdskes commented on deploy.sh
> +git rm -rf public/*
No, we want to preserve `public/.git`

2017-03-18 00:49 UTC, Hjdskes approved these changes

2017-03-18 00:51 UTC, Hjdskes commented
Merged by c24d891aeaf46c843bd9598fe239c541632bb945; I squashed your commits into one and gave it a clearer commit message. Thanks again!

2017-03-18 00:51 UTC, closed without merging